// react-app/src/App.jsx
import React, { useState } from 'react';
import ErrorPage from './components/ErrorPage';

const defaultParams = {
  title: 'It looks empty here...',
  error_code: 200,
  domain: null, // Defaults to current hostname (window.location.hostname)
  time: null, // Defaults to current UTC time
  ray_id: null, // Defaults to random hex
  client_ip: '127.0.0.1',

  more_information: {
    hidden: false,
    text: "cloudflare.com",
    link: "https://www.cloudflare.com",
  },

  browser_status: {
    status: 'ok',
    status_text: 'Working',
    location: 'You',
    name: 'Browser',
  },
  cloudflare_status: {
    status: 'ok',
    status_text: 'Working',
    location: 'Somewhere in the Cloudflare Network',
    name: 'Cloudflare',
  },
  host_status: {
    status: 'ok',
    status_text: 'Working',
    name: 'Host',
  },
  error_source: 'host',

  what_happened: '<p>This domain is working fine but nothing in this place. Because author of this site is too lazy.</p>',
  what_can_i_do: '<p>Please try again in a few months.</p>',

  perf_sec_by: {
    text: "Cloudflare",
    link: "https://www.cloudflare.com",
  },
};

const catastrophicParams = {
  title: 'Catastrophic infrastructure failure',
  error_code: 503,
  more_information: {
    text: "cloudflare.com",
    link: "https://youtube.com/watch?v=dQw4w9WgXcQ",
  },
  browser_status: { status: 'error', status_text: 'Out of Memory', location: 'Your Device', name: 'Browser' },
  cloudflare_status: { status: 'error', location: 'Global Network', status_text: 'Critical Failure', name: 'Cloudflare' },
  host_status: { status: 'error', location: 'Origin Server', status_text: 'On Fire', name: 'Host' },
  error_source: 'cloudflare',
  what_happened: '<p>There is a catastrophic failure.</p>',
  what_can_i_do: '<p>Please try again in a few years.</p>',
  perf_sec_by: {
    text: "Cloudflare",
    link: "https://youtube.com/watch?v=dQw4w9WgXcQ",
  },
};

const workingParams = {
  title: 'Web server is working',
  error_code: 200,
  more_information: { hidden: true },
  browser_status: { status: 'ok', status_text: 'Seems Working', location: 'You', name: 'Browser' },
  cloudflare_status: { status: 'ok', status_text: 'Often Working', location: 'Cloud', name: 'Cloudflare' },
  host_status: { status: 'ok', status_text: 'Just Working', name: 'Host' },
  error_source: 'host',
  what_happened: '<p>This site is still working. And it looks great.</p>',
  what_can_i_do: '<p>Visit the site before it crashes someday.</p>',
};

import './styles/demo.css';

// Simple deep merge function
function deepMerge(target, source) {
  const output = { ...target };
  if (isObject(target) && isObject(source)) {
    Object.keys(source).forEach(key => {
      if (isObject(source[key])) {
        if (!(key in target)) {
          Object.assign(output, { [key]: source[key] });
        } else {
          output[key] = deepMerge(target[key], source[key]);
        }
      } else {
        Object.assign(output, { [key]: source[key] });
      }
    });
  }
  return output;
}

function isObject(item) {
  return (item && typeof item === 'object' && !Array.isArray(item));
}

function getParamsFromEnv() {
  const envConfig = import.meta.env.VITE_CONFIG_JSON;
  if (envConfig) {
    try {
      const parsedConfig = JSON.parse(envConfig);
      console.log("Loaded config from VITE_CONFIG_JSON:", parsedConfig);
      return deepMerge(defaultParams, parsedConfig);
    } catch (e) {
      console.error("Failed to parse VITE_CONFIG_JSON:", e);
    }
  }
  return defaultParams;
}

function App() {
  const [params, setParams] = useState(getParamsFromEnv());
  const isDevelopment = import.meta.env.DEV; // Vite 自動提供

  return (
    <div>
      {isDevelopment && <div className="demo-controller-trigger"></div>}
      {isDevelopment && (
        <div className="demo-controller">
          <span>Select Scenario:</span>
          <button onClick={() => setParams(defaultParams)}>Default (500)</button>
          <button onClick={() => setParams(catastrophicParams)}>Catastrophic</button>
          <button onClick={() => setParams(workingParams)}>Working (200)</button>
        </div>
      )}

      <div>
        <ErrorPage params={params} />
      </div>
    </div>
  );
}

export default App;

// vue-app/src/App.vue
<template>
  <div>
    <div v-if="isDevelopment" class="demo-controller-trigger"></div>
    <div v-if="isDevelopment" class="demo-controller">
      <span>Select Scenario:</span>
      <button @click="params = defaultParams">Default (500)</button>
      <button @click="params = catastrophicParams">Catastrophic</button>
      <button @click="params = workingParams">Working (200)</button>
    </div>

    <div>
      <ErrorPage :params="params" />
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import ErrorPage from './components/ErrorPage.vue';
import './styles/demo.css';

const defaultParams = {
  title: 'It looks empty here...',
  error_code: 200,
  domain: null, // Defaults to current hostname (window.location.hostname)
  time: null, // Defaults to current UTC time
  ray_id: null, // Defaults to random hex
  client_ip: '127.0.0.1',

  more_information: {
    hidden: false,
    text: "cloudflare.com",
    link: "https://www.cloudflare.com",
  },

  browser_status: {
    status: 'ok',
    status_text: 'Working',
    location: 'You',
    name: 'Browser',
  },
  cloudflare_status: {
    status: 'ok',
    status_text: 'Working',
    location: 'Somewhere in the Cloudflare Network',
    name: 'Cloudflare',
  },
  host_status: {
    status: 'ok',
    status_text: 'Working',
    name: 'Host',
  },
  error_source: 'host',

  what_happened: '<p>This domain is working fine but nothing in this place. Because author of this site is too lazy.</p>',
  what_can_i_do: '<p>Please try again in a few months.</p>',

  perf_sec_by: {
    text: "Cloudflare",
    link: "https://www.cloudflare.com",
  },
};

const catastrophicParams = {
  title: 'Catastrophic infrastructure failure',
  error_code: 503,
  more_information: {
    text: "cloudflare.com",
    link: "https://youtube.com/watch?v=dQw4w9WgXcQ",
  },
  browser_status: { status: 'error', status_text: 'Out of Memory', location: 'Your Device', name: 'Browser' },
  cloudflare_status: { status: 'error', location: 'Global Network', status_text: 'Critical Failure', name: 'Cloudflare' },
  host_status: { status: 'error', location: 'Origin Server', status_text: 'On Fire', name: 'Host' },
  error_source: 'cloudflare',
  what_happened: '<p>There is a catastrophic failure.</p>',
  what_can_i_do: '<p>Please try again in a few years.</p>',
  perf_sec_by: {
    text: "Cloudflare",
    link: "https://youtube.com/watch?v=dQw4w9WgXcQ",
  },
};

const workingParams = {
  title: 'Web server is working',
  error_code: 200,
  more_information: { hidden: true },
  browser_status: { status: 'ok', status_text: 'Seems Working', location: 'You', name: 'Browser' },
  cloudflare_status: { status: 'ok', status_text: 'Often Working', location: 'Cloud', name: 'Cloudflare' },
  host_status: { status: 'ok', status_text: 'Just Working', name: 'Host' },
  error_source: 'host',
  what_happened: '<p>This site is still working. And it looks great.</p>',
  what_can_i_do: '<p>Visit the site before it crashes someday.</p>',
};

// Simple deep merge function
function deepMerge(target, source) {
  const output = { ...target };
  if (isObject(target) && isObject(source)) {
    Object.keys(source).forEach(key => {
      if (isObject(source[key])) {
        if (!(key in target)) {
          Object.assign(output, { [key]: source[key] });
        } else {
          output[key] = deepMerge(target[key], source[key]);
        }
      } else {
        Object.assign(output, { [key]: source[key] });
      }
    });
  }
  return output;
}

function isObject(item) {
  return (item && typeof item === 'object' && !Array.isArray(item));
}

function getParamsFromEnv() {
  const envConfig = import.meta.env.VITE_CONFIG_JSON;
  if (envConfig) {
    try {
      const parsedConfig = JSON.parse(envConfig);
      console.log("Loaded config from VITE_CONFIG_JSON:", parsedConfig);
      return deepMerge(defaultParams, parsedConfig);
    } catch (e) {
      console.error("Failed to parse VITE_CONFIG_JSON:", e);
    }
  }
  return defaultParams;
}

const params = ref(getParamsFromEnv());
const isDevelopment = import.meta.env.VITE_DEV === 'true';
</script>
